version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    container_name:  ${DOCKER_NAME}-nginx
    ports:
      - 8002:80
    volumes:
      - ./api:/var/www/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - gradient-maker-network

  api:
    build:
      args:
        user: laraveluser
        uid: 1000
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: ${DOCKER_NAME}-api
    working_dir: /var/www/api
    volumes:
      - ./api:/var/www/api
    networks:
      - gradient-maker-network

  mysql:
    image: mysql:5.7
    container_name: ${DOCKER_NAME}-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      SERVICE_NAME: mysql
    ports:
      - 33269:3306
    volumes:
      - mysql_dbdata:/var/lib/mysql
      - ./docker/mysql/:/docker-entrypoint-initdb.d
    networks:
      - gradient-maker-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${DOCKER_NAME}-phpmyadmin"
    ports:
      - "7000:80"
    links:
      - mysql:mysql
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      PMA_HOST: mysql
    networks:
      - gradient-maker-network

networks: 
  gradient-maker-network:
    driver: bridge

volumes:
    mysql_dbdata: